export {default as Login} from './Login/Login';
// export {default as CarouselBeforeLogin} from './CarouselBeforeLogin/CarouselBeforeLogin';
export {default as OtpVerification} from './OtpVerification/OtpVerification';
export {default as OuterScreen} from './OuterScreen/OuterScreen';
export {default as Home} from './Home/Home';
export {default as Categories} from './Categories/Categories';
export {default as Explore} from './Explore/Explore';
export {default as Profile} from './Profile/Profile';
export {default as ProductDetails} from './ProductDetails/ProductDetails';
export {default as ShowCart} from './ShowCart/ShowCart';
