export default {
  CAROUSELBEFORELOGIN: 'carouselbeforelogin',
  LOGIN: 'login',
  OTP_VERIFICATION: 'otpVerfication',
  OUTER_SCREEN: 'outerScreen',
  HOME: 'Home',
  PRODUCTDETAILS: 'ProductDetails',
  ORDER: 'Order',
  OFFERS: 'offers',
  BRANDS: 'brands',
  CELEBRITY: 'celebrity',
  ACCOUNTS: 'accounts',
  TAB_ROUTES: 'tabRoutes',
  DELIVERY: 'delivery',
  RESTAURANT: 'restaurent',
  SUPERMARKET: 'supermarket',
  SUPERMARKET_PRODUCTS_CATEGORY: 'supermarketProductsCategory',
  PRODUCT_LIST: 'productList',
  CATEGORIES: 'categories',
  PROFILE: 'Profile',
  EXPLORE: 'explore',
  SHOWCART: 'showcart',
  SEARCH: 'Search',
  LEFT_DRAWER: 'leftDrawer',
  CHART: 'Chart',
  QR_CODE: 'Qr Code',
  IMAGE_ZOOM: 'Image Zoom',
  CHAT: 'chat',
  CHAT_DETAILS: 'Chat Details'
};
