export default {
  CAROUSELBEFORELOGIN: 'carouselbeforelogin',
  LOGIN: 'login',
  OTP_VERIFICATION: 'otpVerfication',
  OUTER_SCREEN: 'outerScreen',
  SIGN_UP: 'SignUp',
  HOME: 'Home',
  PRODUCT_DETAILS: 'ProductDetails',
  ORDER: 'Order',
  OFFERS: 'offers',
  BRANDS: 'brands',
  CELEBRITY: 'celebrity',
  ACCOUNTS: 'accounts',
  TAB_ROUTES: 'tabRoutes',
  DELIVERY: 'delivery',
  RESTAURANT: 'restaurent',
  SUPERMARKET: 'supermarket',
  SUPERMARKET_PRODUCTS_CATEGORY: 'supermarketProductsCategory',
  PRODUCT_LIST: 'productList',
  ACCOUNT: 'account',
  CATEGORIES: 'categories',
  PROFILE: 'profile',
};
